In [1]:
import numpy as np
import pandas as pd

In [2]:
feature_columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age','Target']

In [3]:
df = pd.read_csv("../input/pima-indian-diabetes/pima-indians-diabetes.csv",header=None, names=feature_columns)
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Target  
0                     0.627   50       1  
1                     0.351   31       0  
2                     0.672   32       1  
3                     0.167   21       0  
4                     2.288   33       1

In [4]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Target                      0
dtype: int64

In [5]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Target  
0                     0.627   50       1  
1                     0.351   31       0  
2                     0.672   32       1  
3                     0.167   21       0  
4                     2.288   33       1

In [6]:
x3=df.iloc[:,0:8]
y3=df.iloc[:,[8]]


In [7]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn import datasets

from sklearn.model_selection import train_test_split

from sklearn import metrics

In [8]:
x3_train, x3_test, y3_train, y3_test = train_test_split(x3, y3, test_size=0.3)

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report


def evaluate(model, x3_train, x3_test, y3_train, y3_test):
    y3_test_pred = model.predict(x3_test)
    y3_train_pred = model.predict(x3_train)

    print("TRAINIG RESULTS: \n===============================")
    clf_report = pd.DataFrame(classification_report(y3_train, y3_train_pred, output_dict=True))
    print(f"CONFUSION MATRIX:\n{confusion_matrix(y3_train, y3_train_pred)}")
    print(f"ACCURACY SCORE:\n{accuracy_score(y3_train, y3_train_pred):.4f}")
    print(f"CLASSIFICATION REPORT:\n{clf_report}")

    print("TESTING RESULTS: \n===============================")
    clf_report = pd.DataFrame(classification_report(y3_test, y3_test_pred, output_dict=True))
    print(f"CONFUSION MATRIX:\n{confusion_matrix(y3_test, y3_test_pred)}")
    print(f"ACCURACY SCORE:\n{accuracy_score(y3_test, y3_test_pred):.4f}")
    print(f"CLASSIFICATION REPORT:\n{clf_report}")

In [10]:
from sklearn.ensemble import AdaBoostClassifier

ada_boost_clf = AdaBoostClassifier(n_estimators=30)
ada_boost_clf.fit(x3_train, y3_train)
evaluate(ada_boost_clf, x3_train, x3_test, y3_train, y3_test)

TRAINIG RESULTS: 
CONFUSION MATRIX:
[[306  42]
 [ 46 143]]
ACCURACY SCORE:
0.8361
CLASSIFICATION REPORT:
                    0           1  accuracy   macro avg  weighted avg
precision    0.869318    0.772973  0.836127    0.821146      0.835409
recall       0.879310    0.756614  0.836127    0.817962      0.836127
f1-score     0.874286    0.764706  0.836127    0.819496      0.835719
support    348.000000  189.000000  0.836127  537.000000    537.000000
TESTING RESULTS: 
CONFUSION MATRIX:
[[125  27]
 [ 31  48]]
ACCURACY SCORE:
0.7489
CLASSIFICATION REPORT:
                    0          1  accuracy   macro avg  weighted avg
precision    0.801282   0.640000  0.748918    0.720641      0.746125
recall       0.822368   0.607595  0.748918    0.714982      0.748918
f1-score     0.811688   0.623377  0.748918    0.717532      0.747287
support    152.000000  79.000000  0.748918  231.000000    231.000000


/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [11]:

scores = {
        'Train': accuracy_score(y3_train, ada_boost_clf.predict(x3_train)),
        'Test': accuracy_score(y3_test, ada_boost_clf.predict(x3_test)),
    }
print("Scores AdaBoost:",scores)

Scores AdaBoost: {'Train': 0.8361266294227188, 'Test': 0.7489177489177489}


In [12]:
from sklearn.ensemble import GradientBoostingClassifier

grad_boost_clf = GradientBoostingClassifier(n_estimators=100, random_state=42)
grad_boost_clf.fit(x3_train, y3_train)
evaluate(grad_boost_clf, x3_train, x3_test, y3_train, y3_test)

/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


TRAINIG RESULTS: 
CONFUSION MATRIX:
[[342   6]
 [ 23 166]]
ACCURACY SCORE:
0.9460
CLASSIFICATION REPORT:
                    0           1  accuracy   macro avg  weighted avg
precision    0.936986    0.965116  0.945996    0.951051      0.946887
recall       0.982759    0.878307  0.945996    0.930533      0.945996
f1-score     0.959327    0.919668  0.945996    0.939497      0.945369
support    348.000000  189.000000  0.945996  537.000000    537.000000
TESTING RESULTS: 
CONFUSION MATRIX:
[[122  30]
 [ 35  44]]
ACCURACY SCORE:
0.7186
CLASSIFICATION REPORT:
                    0          1  accuracy   macro avg  weighted avg
precision    0.777070   0.594595  0.718615    0.685832      0.714665
recall       0.802632   0.556962  0.718615    0.679797      0.718615
f1-score     0.789644   0.575163  0.718615    0.682404      0.716293
support    152.000000  79.000000  0.718615  231.000000    231.000000


In [13]:
scores['Gradient Boosting'] = {
        'Train': accuracy_score(y3_train, grad_boost_clf.predict(x3_train)),
        'Test': accuracy_score(y3_test, grad_boost_clf.predict(x3_test)),
    }
print( "Gradient Boosting:",scores['Gradient Boosting'])

Gradient Boosting: {'Train': 0.9459962756052142, 'Test': 0.7186147186147186}
